// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: faucet.sql

package store

import (
	"context"
)

const getLastClaim = `-- name: GetLastClaim :one
SELECT address, last_claim_at FROM faucet_claims WHERE address = $1
`

func (q *Queries) GetLastClaim(ctx context.Context, address string) (FaucetClaim, error) {
	row := q.db.QueryRow(ctx, getLastClaim, address)
	var i FaucetClaim
	err := row.Scan(&i.Address, &i.LastClaimAt)
	return i, err
}

const upsertClaim = `-- name: UpsertClaim :exec
INSERT INTO faucet_claims (address, last_claim_at)
VALUES ($1, now())
ON CONFLICT (address) DO UPDATE SET last_claim_at = EXCLUDED.last_claim_at
`

func (q *Queries) UpsertClaim(ctx context.Context, address string) error {
	_, err := q.db.Exec(ctx, upsertClaim, address)
	return err
}
