// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer_state.sql

package store

import (
	"context"
)

const getLastBlock = `-- name: GetLastBlock :one
SELECT value FROM indexer_state WHERE key = 'last_block'
`

func (q *Queries) GetLastBlock(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLastBlock)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const setLastBlock = `-- name: SetLastBlock :exec
INSERT INTO indexer_state (key, value)
VALUES ('last_block', $1)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

func (q *Queries) SetLastBlock(ctx context.Context, value int64) error {
	_, err := q.db.Exec(ctx, setLastBlock, value)
	return err
}
