// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FaucetClaim struct {
	Address     string             `json:"address"`
	LastClaimAt pgtype.Timestamptz `json:"last_claim_at"`
}

type IndexerState struct {
	Key   string `json:"key"`
	Value int64  `json:"value"`
}

type OracleRun struct {
	ID        int64              `json:"id"`
	ZoneID    int16              `json:"zone_id"`
	DayIndex  int32              `json:"day_index"`
	SubmitTx  pgtype.Text        `json:"submit_tx"`
	SettleTx  pgtype.Text        `json:"settle_tx"`
	Status    string             `json:"status"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payout struct {
	ID          int64              `json:"id"`
	PolicyID    int64              `json:"policy_id"`
	Holder      string             `json:"holder"`
	ZoneID      int16              `json:"zone_id"`
	DayIndex    int32              `json:"day_index"`
	Mm          int32              `json:"mm"`
	Amount      pgtype.Numeric     `json:"amount"`
	TxHash      string             `json:"tx_hash"`
	Explanation pgtype.Text        `json:"explanation"`
	ExplainedAt pgtype.Timestamptz `json:"explained_at"`
}

type Policy struct {
	PolicyID    int64          `json:"policy_id"`
	Holder      string         `json:"holder"`
	ZoneID      int16          `json:"zone_id"`
	StartDay    int32          `json:"start_day"`
	EndDay      int32          `json:"end_day"`
	PremiumPaid pgtype.Numeric `json:"premium_paid"`
	TxHash      string         `json:"tx_hash"`
	BlockNumber int64          `json:"block_number"`
}

type Premium struct {
	ZoneID           int16              `json:"zone_id"`
	Month            int16              `json:"month"`
	ExpectedRainDays pgtype.Numeric     `json:"expected_rain_days"`
	PremiumPerWeek   pgtype.Numeric     `json:"premium_per_week"`
	NarrativeID      string             `json:"narrative_id"`
	ComputedAt       pgtype.Timestamptz `json:"computed_at"`
	OnChainTx        pgtype.Text        `json:"on_chain_tx"`
}

type RainObservation struct {
	ZoneID    int16              `json:"zone_id"`
	DayIndex  int32              `json:"day_index"`
	Mm        int32              `json:"mm"`
	Source    string             `json:"source"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type Zone struct {
	ID             int16          `json:"id"`
	Name           string         `json:"name"`
	Lat            float64        `json:"lat"`
	Lon            float64        `json:"lon"`
	ThresholdMm    int32          `json:"threshold_mm"`
	PayoutPerDay   pgtype.Numeric `json:"payout_per_day"`
	MaxDaysPerWeek int16          `json:"max_days_per_week"`
	Active         bool           `json:"active"`
}
