// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oracle_runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOracleRun = `-- name: GetOracleRun :one
SELECT id, zone_id, day_index, submit_tx, settle_tx, status, error, created_at
FROM oracle_runs
WHERE zone_id = $1 AND day_index = $2
`

type GetOracleRunParams struct {
	ZoneID   int16 `json:"zone_id"`
	DayIndex int32 `json:"day_index"`
}

func (q *Queries) GetOracleRun(ctx context.Context, arg GetOracleRunParams) (OracleRun, error) {
	row := q.db.QueryRow(ctx, getOracleRun, arg.ZoneID, arg.DayIndex)
	var i OracleRun
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.DayIndex,
		&i.SubmitTx,
		&i.SettleTx,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOracleRun = `-- name: UpsertOracleRun :one
INSERT INTO oracle_runs (zone_id, day_index, submit_tx, settle_tx, status, error, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (zone_id, day_index) DO UPDATE SET
    submit_tx = COALESCE(EXCLUDED.submit_tx, oracle_runs.submit_tx),
    settle_tx = COALESCE(EXCLUDED.settle_tx, oracle_runs.settle_tx),
    status    = EXCLUDED.status,
    error     = EXCLUDED.error
RETURNING id, zone_id, day_index, submit_tx, settle_tx, status, error, created_at
`

type UpsertOracleRunParams struct {
	ZoneID   int16       `json:"zone_id"`
	DayIndex int32       `json:"day_index"`
	SubmitTx pgtype.Text `json:"submit_tx"`
	SettleTx pgtype.Text `json:"settle_tx"`
	Status   string      `json:"status"`
	Error    pgtype.Text `json:"error"`
}

func (q *Queries) UpsertOracleRun(ctx context.Context, arg UpsertOracleRunParams) (OracleRun, error) {
	row := q.db.QueryRow(ctx, upsertOracleRun,
		arg.ZoneID,
		arg.DayIndex,
		arg.SubmitTx,
		arg.SettleTx,
		arg.Status,
		arg.Error,
	)
	var i OracleRun
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.DayIndex,
		&i.SubmitTx,
		&i.SettleTx,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}
