// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayoutsForZoneDay = `-- name: CountPayoutsForZoneDay :one
SELECT COUNT(*)::bigint
FROM payouts
WHERE zone_id = $1 AND day_index = $2
`

type CountPayoutsForZoneDayParams struct {
	ZoneID   int16 `json:"zone_id"`
	DayIndex int32 `json:"day_index"`
}

func (q *Queries) CountPayoutsForZoneDay(ctx context.Context, arg CountPayoutsForZoneDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayoutsForZoneDay, arg.ZoneID, arg.DayIndex)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listPayoutsForHolder = `-- name: ListPayoutsForHolder :many
SELECT p.id, p.policy_id, p.holder, p.zone_id, p.day_index, p.mm, p.amount, p.tx_hash, p.explanation, p.explained_at,
       z.name AS zone_name
FROM payouts p
JOIN zones z ON z.id = p.zone_id
WHERE p.holder = $1
ORDER BY p.day_index DESC
`

type ListPayoutsForHolderRow struct {
	ID          int64              `json:"id"`
	PolicyID    int64              `json:"policy_id"`
	Holder      string             `json:"holder"`
	ZoneID      int16              `json:"zone_id"`
	DayIndex    int32              `json:"day_index"`
	Mm          int32              `json:"mm"`
	Amount      pgtype.Numeric     `json:"amount"`
	TxHash      string             `json:"tx_hash"`
	Explanation pgtype.Text        `json:"explanation"`
	ExplainedAt pgtype.Timestamptz `json:"explained_at"`
	ZoneName    string             `json:"zone_name"`
}

func (q *Queries) ListPayoutsForHolder(ctx context.Context, holder string) ([]ListPayoutsForHolderRow, error) {
	rows, err := q.db.Query(ctx, listPayoutsForHolder, holder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayoutsForHolderRow
	for rows.Next() {
		var i ListPayoutsForHolderRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Holder,
			&i.ZoneID,
			&i.DayIndex,
			&i.Mm,
			&i.Amount,
			&i.TxHash,
			&i.Explanation,
			&i.ExplainedAt,
			&i.ZoneName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPayout = `-- name: UpsertPayout :exec
INSERT INTO payouts (policy_id, holder, zone_id, day_index, mm, amount, tx_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (policy_id, day_index) DO NOTHING
`

type UpsertPayoutParams struct {
	PolicyID int64          `json:"policy_id"`
	Holder   string         `json:"holder"`
	ZoneID   int16          `json:"zone_id"`
	DayIndex int32          `json:"day_index"`
	Mm       int32          `json:"mm"`
	Amount   pgtype.Numeric `json:"amount"`
	TxHash   string         `json:"tx_hash"`
}

func (q *Queries) UpsertPayout(ctx context.Context, arg UpsertPayoutParams) error {
	_, err := q.db.Exec(ctx, upsertPayout,
		arg.PolicyID,
		arg.Holder,
		arg.ZoneID,
		arg.DayIndex,
		arg.Mm,
		arg.Amount,
		arg.TxHash,
	)
	return err
}
