// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayoutsForPolicyInWeek = `-- name: CountPayoutsForPolicyInWeek :one
SELECT COUNT(*)::bigint
FROM payouts
WHERE policy_id = $1 AND (day_index / 7) = $2
`

type CountPayoutsForPolicyInWeekParams struct {
	PolicyID int64 `json:"policy_id"`
	DayIndex int32 `json:"day_index"`
}

func (q *Queries) CountPayoutsForPolicyInWeek(ctx context.Context, arg CountPayoutsForPolicyInWeekParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayoutsForPolicyInWeek, arg.PolicyID, arg.DayIndex)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActivePolicyForHolder = `-- name: GetActivePolicyForHolder :one
SELECT po.policy_id, po.holder, po.zone_id, po.start_day, po.end_day, z.name AS zone_name, z.max_days_per_week
FROM policies po
JOIN zones z ON z.id = po.zone_id
WHERE po.holder = $1 AND po.end_day > $2
ORDER BY po.start_day DESC
LIMIT 1
`

type GetActivePolicyForHolderParams struct {
	Holder string `json:"holder"`
	EndDay int32  `json:"end_day"`
}

type GetActivePolicyForHolderRow struct {
	PolicyID       int64  `json:"policy_id"`
	Holder         string `json:"holder"`
	ZoneID         int16  `json:"zone_id"`
	StartDay       int32  `json:"start_day"`
	EndDay         int32  `json:"end_day"`
	ZoneName       string `json:"zone_name"`
	MaxDaysPerWeek int16  `json:"max_days_per_week"`
}

func (q *Queries) GetActivePolicyForHolder(ctx context.Context, arg GetActivePolicyForHolderParams) (GetActivePolicyForHolderRow, error) {
	row := q.db.QueryRow(ctx, getActivePolicyForHolder, arg.Holder, arg.EndDay)
	var i GetActivePolicyForHolderRow
	err := row.Scan(
		&i.PolicyID,
		&i.Holder,
		&i.ZoneID,
		&i.StartDay,
		&i.EndDay,
		&i.ZoneName,
		&i.MaxDaysPerWeek,
	)
	return i, err
}

const upsertPolicy = `-- name: UpsertPolicy :exec
INSERT INTO policies (policy_id, holder, zone_id, start_day, end_day, premium_paid, tx_hash, block_number)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (policy_id) DO NOTHING
`

type UpsertPolicyParams struct {
	PolicyID    int64          `json:"policy_id"`
	Holder      string         `json:"holder"`
	ZoneID      int16          `json:"zone_id"`
	StartDay    int32          `json:"start_day"`
	EndDay      int32          `json:"end_day"`
	PremiumPaid pgtype.Numeric `json:"premium_paid"`
	TxHash      string         `json:"tx_hash"`
	BlockNumber int64          `json:"block_number"`
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertPolicy,
		arg.PolicyID,
		arg.Holder,
		arg.ZoneID,
		arg.StartDay,
		arg.EndDay,
		arg.PremiumPaid,
		arg.TxHash,
		arg.BlockNumber,
	)
	return err
}
