// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: premiums.sql

package store

import (
	"context"
)

const getPremiumForZoneMonth = `-- name: GetPremiumForZoneMonth :one
SELECT zone_id, month, expected_rain_days, premium_per_week, narrative_id, computed_at, on_chain_tx
FROM premiums
WHERE zone_id = $1 AND month = $2
`

type GetPremiumForZoneMonthParams struct {
	ZoneID int16 `json:"zone_id"`
	Month  int16 `json:"month"`
}

func (q *Queries) GetPremiumForZoneMonth(ctx context.Context, arg GetPremiumForZoneMonthParams) (Premium, error) {
	row := q.db.QueryRow(ctx, getPremiumForZoneMonth, arg.ZoneID, arg.Month)
	var i Premium
	err := row.Scan(
		&i.ZoneID,
		&i.Month,
		&i.ExpectedRainDays,
		&i.PremiumPerWeek,
		&i.NarrativeID,
		&i.ComputedAt,
		&i.OnChainTx,
	)
	return i, err
}
