// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountPayoutsForPolicyInWeek(ctx context.Context, arg CountPayoutsForPolicyInWeekParams) (int64, error)
	CountPayoutsForZoneDay(ctx context.Context, arg CountPayoutsForZoneDayParams) (int64, error)
	GetActivePolicyForHolder(ctx context.Context, arg GetActivePolicyForHolderParams) (GetActivePolicyForHolderRow, error)
	GetLastBlock(ctx context.Context) (int64, error)
	GetLastClaim(ctx context.Context, address string) (FaucetClaim, error)
	GetOracleRun(ctx context.Context, arg GetOracleRunParams) (OracleRun, error)
	GetPremiumForZoneMonth(ctx context.Context, arg GetPremiumForZoneMonthParams) (Premium, error)
	GetRainObservation(ctx context.Context, arg GetRainObservationParams) (RainObservation, error)
	GetZone(ctx context.Context, id int16) (Zone, error)
	ListActiveZones(ctx context.Context) ([]Zone, error)
	ListPayoutsForHolder(ctx context.Context, holder string) ([]ListPayoutsForHolderRow, error)
	ListRecentRain(ctx context.Context, arg ListRecentRainParams) ([]RainObservation, error)
	SetLastBlock(ctx context.Context, value int64) error
	UpsertClaim(ctx context.Context, address string) error
	UpsertOracleRun(ctx context.Context, arg UpsertOracleRunParams) (OracleRun, error)
	UpsertPayout(ctx context.Context, arg UpsertPayoutParams) error
	UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error
	UpsertRainObservation(ctx context.Context, arg UpsertRainObservationParams) error
}

var _ Querier = (*Queries)(nil)
