// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rain.sql

package store

import (
	"context"
)

const getRainObservation = `-- name: GetRainObservation :one
SELECT zone_id, day_index, mm, source, fetched_at
FROM rain_observations
WHERE zone_id = $1 AND day_index = $2
`

type GetRainObservationParams struct {
	ZoneID   int16 `json:"zone_id"`
	DayIndex int32 `json:"day_index"`
}

func (q *Queries) GetRainObservation(ctx context.Context, arg GetRainObservationParams) (RainObservation, error) {
	row := q.db.QueryRow(ctx, getRainObservation, arg.ZoneID, arg.DayIndex)
	var i RainObservation
	err := row.Scan(
		&i.ZoneID,
		&i.DayIndex,
		&i.Mm,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const listRecentRain = `-- name: ListRecentRain :many
SELECT zone_id, day_index, mm, source, fetched_at
FROM rain_observations
WHERE zone_id = $1
ORDER BY day_index DESC
LIMIT $2
`

type ListRecentRainParams struct {
	ZoneID int16 `json:"zone_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListRecentRain(ctx context.Context, arg ListRecentRainParams) ([]RainObservation, error) {
	rows, err := q.db.Query(ctx, listRecentRain, arg.ZoneID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RainObservation
	for rows.Next() {
		var i RainObservation
		if err := rows.Scan(
			&i.ZoneID,
			&i.DayIndex,
			&i.Mm,
			&i.Source,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRainObservation = `-- name: UpsertRainObservation :exec
INSERT INTO rain_observations (zone_id, day_index, mm, source, fetched_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (zone_id, day_index) DO UPDATE SET
    mm         = EXCLUDED.mm,
    source     = EXCLUDED.source,
    fetched_at = EXCLUDED.fetched_at
`

type UpsertRainObservationParams struct {
	ZoneID   int16  `json:"zone_id"`
	DayIndex int32  `json:"day_index"`
	Mm       int32  `json:"mm"`
	Source   string `json:"source"`
}

func (q *Queries) UpsertRainObservation(ctx context.Context, arg UpsertRainObservationParams) error {
	_, err := q.db.Exec(ctx, upsertRainObservation,
		arg.ZoneID,
		arg.DayIndex,
		arg.Mm,
		arg.Source,
	)
	return err
}
