// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zones.sql

package store

import (
	"context"
)

const getZone = `-- name: GetZone :one
SELECT id, name, lat, lon, threshold_mm, payout_per_day, max_days_per_week, active
FROM zones
WHERE id = $1
`

func (q *Queries) GetZone(ctx context.Context, id int16) (Zone, error) {
	row := q.db.QueryRow(ctx, getZone, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.ThresholdMm,
		&i.PayoutPerDay,
		&i.MaxDaysPerWeek,
		&i.Active,
	)
	return i, err
}

const listActiveZones = `-- name: ListActiveZones :many
SELECT id, name, lat, lon, threshold_mm, payout_per_day, max_days_per_week, active
FROM zones
WHERE active = TRUE
ORDER BY id
`

func (q *Queries) ListActiveZones(ctx context.Context) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listActiveZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.ThresholdMm,
			&i.PayoutPerDay,
			&i.MaxDaysPerWeek,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
